NODERS
stakeme-team/story-validators-race pull request #11
Opened 2024-09-06 04:02 UTC by nodersteam

2024-09-06 05:20 UTC, icodragon approved these changes
Hey, can you fill in README.md about your validator, please

2024-09-07 06:14 UTC, nodersteam commented
> Hey, can you fill in README.md about your validator, please

Done

2024-09-07 07:39 UTC, icodragon requested changes
@nodersteam please add links to validated networks and links to your project, products (if any)

2024-09-07 08:28 UTC, icodragon approved these changes

2024-09-07 08:28 UTC, merged