kjnodes: submit task 2
stakeme-team/story-validators-race pull request #201
Opened 2024-09-08 18:11 UTC by kj89

2024-09-09 04:06 UTC, Immertion commented
@icodragon endpoints checked

2024-09-09 04:55 UTC, icodragon approved these changes

2024-09-09 07:29 UTC, icodragon requested changes
Hello @kj89 
Please submit one submission - one PR

2024-09-09 16:22 UTC, kj89 commented
> Hello @kj89 Please submit one submission - one PR

removed task 3 please merge 🙏

2024-09-10 03:49 UTC, icodragon approved these changes

2024-09-10 03:49 UTC, merged