BlockHub Task 1
stakeme-team/story-validators-race pull request #63
Opened 2024-09-06 16:40 UTC by botxx15

2024-09-06 16:58 UTC, icodragon requested changes
Hello! @botxx15
Can you describe your validator in more detail, please (ex. see examples of other PRs)

2024-09-06 17:12 UTC, botxx15 commented
Hi @icodragon, can you please elaborate more? Do you mean provide the links for all of my validators? If so, the images are clickable and it will direct you to all of my validators that I participated.

2024-09-07 00:21 UTC, botxx15 commented
Hi @icodragon can you please check again? Thank you

2024-09-07 07:33 UTC, icodragon approved these changes

2024-09-07 07:33 UTC, merged