Synergy_Nodes Task1
stakeme-team/story-validators-race pull request #68
Opened 2024-09-06 16:57 UTC by SynergyNodes

2024-09-06 17:03 UTC, icodragon requested changes
Hello @SynergyNodes 
Can you describe your validator in more detail, please (ex. see examples of other PRs)

2024-09-06 17:21 UTC, SynergyNodes commented
Hello @icodragon ,

I have added more details about us.

Regards,
Aries

2024-09-06 17:43 UTC, SynergyNodes commented
Hello @icodragon 

We have updated our details. Thank You.

Regards,
Aries

2024-09-07 07:37 UTC, icodragon approved these changes

2024-09-07 07:37 UTC, merged