dhozil Validator Task 1
stakeme-team/story-validators-race pull request #93
Opened 2024-09-07 04:16 UTC by dhozil

2024-09-07 15:04 UTC, icodragon requested changes
Hello! @dhozil
Can you describe your validator in more detail, please (ex. see examples of other PRs)

2024-09-07 16:14 UTC, dhozil commented
> Hello! @dhozil Can you describe your validator in more detail, please (ex. see examples of other PRs)

updated

2024-09-08 15:49 UTC, dhozil commented
can i get merged? to complete next task

2024-09-09 03:48 UTC, icodragon approved these changes

2024-09-09 03:48 UTC, merged